### ISSUE TITLE
Name for this organization

### ISSUE THREAD

**Issue by tute** [osscommunity/starters#7]
Should we rename this organization from "osstarter" to "osscommunity"? That way we are explicit about the fact that some resources here are useful for maintainers too.

**Comment by afeld** [comment]
:+1:

**Comment by afeld** [comment]
We should probably rename this repo too..."newbies"?

**Comment by tute** [comment]
Starters sound better?

**Comment by afeld** [comment]
Works for me! Going once, going twice...?

**Comment by tute** [comment]
Done!

**Comment by tute** [comment]
https://github.com/osscommunity/starters/issues/8 should belong in a new repo "maintainers". Can we "move" an issue?

**Comment by afeld** [comment]
No – I'd just open a new one and cross-link them.
